# Generated by Django 5.1.1 on 2024-10-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'FIAT'), (4, 'HONDA'), (5, 'HYUNDAI')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'BRANCO'), (2, 'AMARELO'), (3, 'AZUL'), (4, 'PRATA')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='veiculo/fotos')),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel')])),
            ],
        ),
    ]
